#!/bin/sh
# ALIASES FOR GIT
alias \
    gs="git status" \
    ga="git add" \
    gc="git commit" \
    gpo="git push origin main" \
    gp="git push" \
    gd="git diff" \
    gr="git remote -v" \
    gch="git checkout" \
    gl="git log" \
    gra="git remote add origin" \
    grv="git remote remove origin" \
    gi="git init"
    gb="git branch"

# ALIASES FOR CONFIG
alias \
    cs="config status" \
    ca="config add" \
    cc="config commit" \
    cps="config push origin main" \
    cdf="config diff"

# EXTRA
alias \
    ..='cd ..' \
    ...='cd ../..' \
    pi='sudo pacman -S' \
    pr='sudo pacman -Rns' \
    pu="yay -Syu" \
    ps='pacman -Ss' \
    pq='pacman -Qs' \
    ls='ls -lh --color=auto -Ivenv -I__pycache__ -I__init__.py -Inode_modules' \
    ll='ls -al --color=auto' \
    mi='sudo make clean install' \
    sc="cd ~/.local/bin" \
    dw="cd ~/suckless/dwm" \
    sk="cd ~/suckless" \
    config="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME" \
    vac="source venv/bin/activate" \
    tmux="tmux -f $HOME/.config/tmux.conf" \
    mkdir='mkdir -pv'

se(){ 
    file=$(find $HOME/.local/bin $HOME/.config -maxdepth 2 | grep -v "libreoffice\|VirtualBox" | fzf)
    [ "$file" ] && nvim $file
}
sf(){
    directory=$(find $HOME/.local/bin $HOME/.config -maxdepth 2 | grep -v "libreoffice\|VirtualBox" | fzf)
    [ "$directory" ] && cd $directory
}
de() { 
    dir=$(/usr/bin/ls -d -1 "$HOME/Documents/code/python_projects/"* "$HOME/Documents/code/learning/"* | fzf)
    name=$(echo $dir | awk -F "/" '{ print $NF }')
    [ "$dir" ] && pushd $dir > /dev/null && \
    tmux new -s "$name" && \
    popd > /dev/null
}
gprev(){
    read -p "Enter commit hash: " commit_hash
    git checkout $commit_hash
    git branch -D main
    git switch -c main
}
