#!/bin/sh
# ALIASES FOR GIT
alias \
    gs="git status" \
    ga="git add" \
    gc="git commit" \
    gp="git push origin main" \
    gd="git diff" \
    gr="git remote -v" \
    gch="git checkout" \
    gl="git log" \
    gra="git remote add origin" \
    grv="git remote remove origin" \
    gi="git init"

# ALIASES FOR CONFIG
alias \
    cs="config status" \
    ca="config add" \
    cc="config commit" \
    cps="config push origin main" \
    cdf="config diff"

# EXTRA
alias \
    ls='ls --color=auto' \
    ll='ls -al --color=auto' \
    mi='sudo make clean install' \
    sc="cd ~/.local/bin" \
    dw="cd ~/suckless/dwm" \
    sk="cd ~/suckless" \
    mv="mv -i" \
    cp="cp -i" \
    rm="rm -i" \
    config="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME" \
    update="yay -Syyu;firefox-updater" \
    find="find -name 2> /dev/null"
