#!/bin/bash
export PATH="$HOME/.local/bin:$PATH"
export EDITOR="nvim"
export HISTFILE="$HOME/.cache/.bash_history"
export FZF_DEFAULT_COMMAND="rg --files --follow --no-ignore-vcs --hidden -g '!node_modules/' -g '!.git' -g '!__pycache__'"
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
