#!/bin/bash
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/lib/nodejs/bin:$PATH"
export EDITOR="nvim"
export TERMINAL="xfce4-terminal"
export HISTFILE="$HOME/.cache/.bash_history"
export FZF_DEFAULT_COMMAND="rg --files --follow --no-ignore-vcs --hidden -g '!node_modules/' -g '!.git' -g '!__pycache__' -g '!__init__.py' -g '!venv' -g '!build'"
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
