#!/bin/sh

# Autostart
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh

# Workspaces
bspc monitor -d 1 2 3 4 5

# BSPWM configuration
bspc config border_width                3
bspc config top_padding                 26
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config window_gap                  5
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config click_to_focus              false

# BSPWM coloring
bspc config normal_border_color		    "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	    "#5e81ac"
