#!/bin/bash
fetched_version=$($HOME/.scripts/get_firefox_version.py)
firefox_version=$($HOME/Applications/firefox/firefox-bin --version)
true_version=${firefox_version:16}
install_firefox="wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/$fetched_version/linux-x86_64/en-US/firefox-$fetched_version.tar.bz2 -P $HOME/Downloads/firefox_releases/ && tar -xvf $HOME/Downloads/firefox_releases/firefox-$fetched_version.tar.bz2 -C $HOME/Applications"
[ "$fetched_version" = "$true_version" ] && echo "firefox is up-to-date" || $install_firefox
